apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newsatlas-ingress
spec:
  rules:
  - host: newsatlas.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: newsatlas-frontend
            port:
              number: 5173
